### ISSUE TITLE
[request] support for a "working-directory" input

### ISSUE THREAD

**Issue by es50678** [corymhall/cdk-diff-action#127]
hi. I like this action but it doesn't seem to work with our repo setups which are generally:

REPO_A:
```
|- cdk/package.json
...
|- package.json
```

we have a mono repo set up and basically want to use this action but we run `cdk synth` within the `cdk` directory.

**Comment by corymhall** [comment]
Hey @es50678 I think it should work if you provide the path to the `cdk.out` directory that you want the action to use. 

```yaml
- name: Diff
        uses: corymhall/cdk-diff-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cdkOutDir: cdk/cdk.out
```
