### ISSUE TITLE
Add support for multiple diffs

### ISSUE THREAD

**Issue by rantoniuk** [corymhall/cdk-diff-action#130]
When having environment-agnostic stacks and hence using only CDK's DefaultStage, currently there is no way to have multiple diffs in the same workflow:

```
jobs:

 dev:
    name: CDK diff DEV
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      ...

      - name: CDK diff
        uses: corymhall/cdk-diff-action@v2-beta
        with:
          githubToken: ${{ steps.ghactions-auth.outputs.token }}
          cdkOutDir: ${{ github.workspace }}/cdk.out
          failOnDestructiveChanges: false

 prod:
    name: CDK diff PROD
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      ...

      - name: CDK diff
        uses: corymhall/cdk-diff-action@v2-beta
        with:
          githubToken: ${{ steps.ghactions-auth.outputs.token }}
          cdkOutDir: ${{ github.workspace }}/cdk.out
          failOnDestructiveChanges: false
```

What I expect here is those two jobs create two distinct comments, based on the environment used. Right now, the action is overwriting the comment content depending on the order of finish.
