### ISSUE TITLE
This action fails on aws-cdk v2.154.1

### ISSUE THREAD

**Issue by noel-cashrewards** [corymhall/cdk-diff-action#74]
I was upgrading my project's CDK version to the latest (v2.154.1) and this action has failed.

```
Run corymhall/cdk-diff-action@v1.2.10
  with:
    failOnDestructiveChanges: false
    githubToken: ***
    noFailOnDestructiveChanges: List of stages where breaking changes will not fail the build
    cdkOutDir: cdk.out
  env:
    AWS_DEFAULT_REGION: ap-southeast-2
    AWS_REGION: ap-southeast-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    ENVIRONMENT_NAME: live
Error performing diff:  Error: Cannot read integ manifest 'cdk.out/manifest.json': Cloud assembly schema version mismatch: Maximum schema version supported is 36.0.0, but found 36.0.16
    at Function.fromFile (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/lib/assembly.js:44:1)
    at Function.fromPath (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/lib/assembly.js:61:1)
    at run (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/lib/action.js:45:1)
    at Object.94822 (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/lib/index.js:28:1)
    at __nccwpck_require__ (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/webpack/bootstrap:21:1)
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/webpack/startup:4:1
    at Object.<anonymous> (/home/runner/work/_actions/corymhall/cdk-diff-action/v1.2.10/dist/index.js:88980:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
```

This is how I use this action.

```yaml
    - name: Diff against prod
        if: steps.diffset.outputs.cdk_files
        uses: corymhall/cdk-diff-action@v1.2.10
        env:
          ENVIRONMENT_NAME: prod
        with:
          failOnDestructiveChanges: false
          githubToken: ${{ secrets.GITHUB_TOKEN }},
```

It was working with no problems with v2.153.0 so I have reverted to that version in the mean time.
