### ISSUE TITLE
GitHub 403 Response - Resource not accessible by integration

### ISSUE THREAD

**Issue by chessbyte** [corymhall/cdk-diff-action#87]
I am running an adapted versions of your first example from [here](https://github.com/corymhall/cdk-diff-action?tab=readme-ov-file#example-configurations) in a private repo in a private GitHub org.

Continuously getting the following error:
  - `Error commenting stages:  RequestError [HttpError]: Resource not accessible by integration - https://docs.github.com/rest/issues/comments#create-an-issue-comment`

My OIDC Auth looks like (and works for deployments via GHA)
```
      - name: Authenticate Via OIDC Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::1234567891012:role/GitHubOidcRole
          aws-region: us-east-1
```

Tried with
```
  permissions:
    contents: read
    id-token: write
    packages: read
    pull-requests: write
```

Tried with
```
  permissions:
    contents: read
    id-token: write
    packages: read
    issues: write
```

Tried with
```
  permissions: write-all
```
